name: umkm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  custom_navigation_bar: ^0.8.2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  rounded_loading_button: ^2.1.0
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
