// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhw2xXRjzJFfMZKBcuXwpViT9sq0_MY0M',
    appId: '1:64498813798:web:42bae3281260c8308f56a7',
    messagingSenderId: '64498813798',
    projectId: 'umkm-pringsewu',
    authDomain: 'umkm-pringsewu.firebaseapp.com',
    storageBucket: 'umkm-pringsewu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9VJvMfU_nzbbx05iwzdDocCnrls_QJ4',
    appId: '1:64498813798:android:c671cc6994bb428b8f56a7',
    messagingSenderId: '64498813798',
    projectId: 'umkm-pringsewu',
    storageBucket: 'umkm-pringsewu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqXvZg2MDw0MBjvVujqWd2IqaVFa7DfHk',
    appId: '1:64498813798:ios:4a75d8f247ea9a8c8f56a7',
    messagingSenderId: '64498813798',
    projectId: 'umkm-pringsewu',
    storageBucket: 'umkm-pringsewu.appspot.com',
    iosClientId:
        '64498813798-pk98ikbhao0llsovkn7ttufgt4cg0gt9.apps.googleusercontent.com',
    iosBundleId: 'com.kentasadisaputra.umkm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqXvZg2MDw0MBjvVujqWd2IqaVFa7DfHk',
    appId: '1:64498813798:ios:4a75d8f247ea9a8c8f56a7',
    messagingSenderId: '64498813798',
    projectId: 'umkm-pringsewu',
    storageBucket: 'umkm-pringsewu.appspot.com',
    iosClientId:
        '64498813798-pk98ikbhao0llsovkn7ttufgt4cg0gt9.apps.googleusercontent.com',
    iosBundleId: 'com.kentasadisaputra.umkm',
  );
}
